"""Add google_calendar_event_id to calendar_events_syfw

Revision ID: 2ef2abc023ae
Revises: 864d6131f965
Create Date: 2025-07-10 14:36:38.616350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef2abc023ae'
down_revision = '864d6131f965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    with op.batch_alter_table('calendar_events_syfw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    with op.batch_alter_table('reminders_syfw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    with op.batch_alter_table('todos_syfw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos_syfw', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    with op.batch_alter_table('reminders_syfw', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    with op.batch_alter_table('calendar_events_syfw', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_event_id')

    # ### end Alembic commands ###
