"""Add blnd_todo tables

Revision ID: 65a32b4dfa30
Revises: 2ef2abc023ae
Create Date: 2025-07-18 01:28:43.560857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a32b4dfa30'
down_revision = '2ef2abc023ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events_blnd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_from', sa.DateTime(), nullable=True),
    sa.Column('event_to', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events_blnd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_blnd_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_blnd_title'), ['title'], unique=False)

    op.create_table('reminders_blnd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_text', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders_blnd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_blnd_id'), ['id'], unique=False)

    op.create_table('todos_blnd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos_blnd', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_blnd_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_blnd_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos_blnd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_blnd_title'))
        batch_op.drop_index(batch_op.f('ix_todos_blnd_id'))

    op.drop_table('todos_blnd')
    with op.batch_alter_table('reminders_blnd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_blnd_id'))

    op.drop_table('reminders_blnd')
    with op.batch_alter_table('calendar_events_blnd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_blnd_title'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_blnd_id'))

    op.drop_table('calendar_events_blnd')
    # ### end Alembic commands ###
