"""Add company to User model

Revision ID: 72034aee5489
Revises: cfd4bffcda59
Create Date: 2025-06-11 13:53:42.991816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72034aee5489'
down_revision = 'cfd4bffcda59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
