"""Add syfw tables

Revision ID: 864d6131f965
Revises: 72034aee5489
Create Date: 2025-07-03 00:14:44.860201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864d6131f965'
down_revision = '72034aee5489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events_syfw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_from', sa.DateTime(), nullable=True),
    sa.Column('event_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events_syfw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_syfw_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_syfw_title'), ['title'], unique=False)

    op.create_table('reminders_syfw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_text', sa.String(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders_syfw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_syfw_id'), ['id'], unique=False)

    op.create_table('todos_syfw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos_syfw', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_syfw_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_syfw_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos_syfw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_syfw_title'))
        batch_op.drop_index(batch_op.f('ix_todos_syfw_id'))

    op.drop_table('todos_syfw')
    with op.batch_alter_table('reminders_syfw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_syfw_id'))

    op.drop_table('reminders_syfw')
    with op.batch_alter_table('calendar_events_syfw', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_syfw_title'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_syfw_id'))

    op.drop_table('calendar_events_syfw')
    # ### end Alembic commands ###
