"""add_call_recordings_lgch_table

Revision ID: f1a2b3c4d5e6
Revises: cfd4bffcda59
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'cfd4bffcda59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_recordings_lgch',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('call_sid', sa.String(), nullable=False),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('recording_path', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'completed'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_index(op.f('ix_call_recordings_lgch_id'), 'call_recordings_lgch', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_recordings_lgch_id'), table_name='call_recordings_lgch')
    op.drop_table('call_recordings_lgch')
    # ### end Alembic commands ###
